version: 2

sources:
  - name: raw
    catalog: hive_metastore
    schema: raw
    tables:
      - name: raw_finance_general_hubchat_escale_finance__attendance
      - name: raw_finance_general_hubchat_escale_finance__messages_context
      - name: raw_finance_general_hubchat_escale_finance__messages_from
      - name: raw_finance_general_hubchat_escale_finance__messages
      - name: raw_finance_general_hubchat_escale_finance__workspace
      - name: raw_homeservices_general_hubchat_chat__attendance
      - name: raw_homeservices_general_hubchat_chat__messages_context_full
      - name: raw_homeservices_general_hubchat_chat__messages_context
      - name: raw_homeservices_general_hubchat_chat__messages_from
      - name: raw_homeservices_general_hubchat_chat__messages
      - name: raw_homeservices_general_hubchat_chat__workspace