version: 2

sources:
  - name: raw
    catalog: hive_metastore
    schema: raw
    tables:
      - name: raw_finance_general_hubchat_escale_finance__attendance
      - name: raw_finance_general_hubchat_escale_finance__messages_context
      - name: raw_finance_general_hubchat_escale_finance__messages_from
      - name: raw_finance_general_hubchat_escale_finance__messages
      - name: raw_finance_general_hubchat_escale_finance__workspace
      - name: raw_homeservices_general_hubchat_chat__attendance
      - name: raw_homeservices_general_hubchat_chat__messages_context
      - name: raw_homeservices_general_hubchat_chat__messages_from
      - name: raw_homeservices_general_hubchat_chat__messages
      - name: raw_homeservices_general_hubchat_chat__workspace

  - name: trusted_finance_general
    catalog: hive_metastore
    schema: trusted_finance_general
    tables:
      - name: hubchat_escale_finance_messages
      - name: hubchat_escale_finance_workspace
      - name: hubchat_escale_finance_attendance
      - name: hubchat_escale_finance_messages_context
      - name: hubchat_escale_finance_messages_from

  - name: trusted_homeservices_general
    catalog: hive_metastore
    schema: trusted_homeservices_general
    tables:
      - name: hubchat_chat_messages
      - name: hubchat_chat_workspace
      - name: google_spreadsheet_hubchat_price
      - name: google_spreadsheet_de_para_digital_campaign
      - name: hubchat_chat_attendance
      - name: hubchat_chat_messages_context
      - name: hubchat_escale_messages_from