with cte_produto_data AS(
    SELECT -2 produto_id, 'TESTE' AS produto
    UNION ALL
    SELECT -1 , 'NAO INFORMADO'
    UNION ALL
    SELECT 1, 'ASSINATURA ENERGIA'
    UNION ALL
    SELECT 2, 'HOMESERVICES'
    UNION ALL
    SELECT 3, 'CONSIGNADO'
    UNION ALL
    SELECT 4, 'CONTA CARTAO'
    UNION ALL
    SELECT 5, 'EGV'
    UNION ALL
    SELECT 6, 'FGTS'
    UNION ALL
    SELECT 7, 'FINANCIAMENTO'
    UNION ALL
    SELECT 9, 'FINANCIAMENTO AUTO'
    UNION ALL
    SELECT 10, 'CONSORCIO'
    UNION ALL
    SELECT 11, 'INTERNET, TV, TELEFONE E MOVEL'
    UNION ALL
    SELECT 12, 'INTERNET'
)
select * from cte_produto_data