with 

source as (

    select * from {{ source('raw', 'raw_finance_itau_hubspot__tickets') }}

),

renamed as (

    select
        archived,
        created_at,
        id,
        lake_created_at,
        updated_at,
        properties_cep_proposta,
        properties_closed_date,
        properties_cpf_proposta,
        properties_createdate,
        properties_data_auditoria_a_realizar,
        properties_data_auditoria_pendente,
        properties_data_auditoria_realizada,
        properties_data_de_cancelamento,
        properties_data_de_nascimento_proposta,
        properties_forma_de_pagamento___ticket,
        properties_grupo,
        properties_hs_all_accessible_team_ids,
        properties_hs_all_associated_contact_emails,
        properties_hs_all_associated_contact_firstnames,
        properties_hs_all_associated_contact_lastnames,
        properties_hs_all_associated_contact_phones,
        properties_hs_all_owner_ids,
        properties_hs_all_team_ids,
        properties_hs_date_entered_11303741,
        properties_hs_date_entered_11303742,
        properties_hs_date_entered_11303743,
        properties_hs_date_entered_11303759,
        properties_hs_date_entered_16911801,
        properties_hs_date_entered_16911802,
        properties_hs_date_entered_16911803,
        properties_hs_date_entered_16911804,
        properties_hs_date_entered_16945800,
        properties_hs_date_entered_17439840,
        properties_hs_date_entered_3660163,
        properties_hs_date_entered_5771053,
        properties_hs_date_entered_8109917,
        properties_hs_date_entered_8649022,
        properties_hs_date_exited_11303741,
        properties_hs_date_exited_11303742,
        properties_hs_date_exited_11303743,
        properties_hs_date_exited_16911801,
        properties_hs_date_exited_16911802,
        properties_hs_date_exited_16911803,
        properties_hs_date_exited_16911804,
        properties_hs_date_exited_16945800,
        properties_hs_date_exited_17439840,
        properties_hs_date_exited_3660163,
        properties_hs_date_exited_5771053,
        properties_hs_date_exited_8109917,
        properties_hs_date_exited_8649022,
        properties_hs_helpdesk_sort_timestamp,
        properties_hs_last_email_activity,
        properties_hs_last_message_from_visitor,
        properties_hs_lastactivitydate,
        properties_hs_lastcontacted,
        properties_hs_lastmodifieddate,
        properties_hs_num_associated_companies,
        properties_hs_num_times_contacted,
        properties_hs_object_id,
        properties_hs_pipeline,
        properties_hs_pipeline_stage,
        properties_hs_ticket_id,
        properties_hs_ticket_priority,
        properties_hs_time_in_11303741,
        properties_hs_time_in_11303742,
        properties_hs_time_in_11303743,
        properties_hs_time_in_11303759,
        properties_hs_time_in_16911801,
        properties_hs_time_in_16911802,
        properties_hs_time_in_16911803,
        properties_hs_time_in_16911804,
        properties_hs_time_in_16945800,
        properties_hs_time_in_17439840,
        properties_hs_time_in_3660163,
        properties_hs_time_in_5771053,
        properties_hs_time_in_8109917,
        properties_hs_time_in_8649022,
        properties_hs_updated_by_user_id,
        properties_hs_user_ids_of_all_owners,
        properties_hubspot_owner_assigneddate,
        properties_hubspot_owner_id,
        properties_hubspot_team_id,
        properties_last_engagement_date,
        properties_negociacao_taxa,
        properties_numero_da_proposta,
        properties_possivel_churn,
        properties_produto_do_consorcio,
        properties_subject,
        properties_time_to_close,
        properties_tipo_do_mob,
        properties_unidade_de_negocio,
        properties_valor,
        month,
        day

    from source

)

select * from renamed
