with 

source as (

    select * from {{ source('raw', 'raw_finance_bv_hubspot__deals') }}

),

renamed as (

    select
        archived,
        created_at,
        id,
        lake_created_at,
        updated_at,
        properties_createdate,
        properties_data_hora___declinado,
        properties_data_hora___negociacao,
        properties_data_hora___tentativa_de_contato,
        properties_days_to_close,
        properties_dealname,
        properties_dealstage,
        properties_fgts_canal_contatado,
        properties_fgts_controle_etapa,
        properties_fgts_data_contatado,
        properties_fgts_data_da_tentativa_de_contato,
        properties_fgts_data_declinado,
        properties_fgts_data_negociacao,
        properties_fgts_etapa_declinado,
        properties_fgts_motivo_declinio,
        properties_fgts_move_declinado_temp,
        properties_fgts_move_negociacao_temp,
        properties_fgts_owner_contatado,
        properties_fgts_owner_declinado,
        properties_fgts_owner_negociacao,
        properties_fgts_owner_tentativa_contato,
        properties_fgts_quantidade_de_parcelas_antecipadas,
        properties_fgts_team_contatado,
        properties_fgts_team_declinado,
        properties_fgts_team_negociacao,
        properties_fgts_team_tentativa_contato,
        properties_fgts_tipo_lead,
        properties_fgts_valor_contratado,
        properties_fgts_valor_solicitado,
        properties_hs_all_accessible_team_ids,
        properties_hs_all_owner_ids,
        properties_hs_all_team_ids,
        properties_hs_analytics_latest_source,
        properties_hs_analytics_latest_source_contact,
        properties_hs_analytics_latest_source_data_1,
        properties_hs_analytics_latest_source_data_1_contact,
        properties_hs_analytics_latest_source_data_2,
        properties_hs_analytics_latest_source_data_2_contact,
        properties_hs_analytics_latest_source_timestamp,
        properties_hs_analytics_latest_source_timestamp_contact,
        properties_hs_analytics_source,
        properties_hs_analytics_source_data_1,
        properties_hs_analytics_source_data_2,
        properties_hs_closed_amount,
        properties_hs_closed_amount_in_home_currency,
        properties_hs_createdate,
        properties_hs_date_entered_30258471,
        properties_hs_date_entered_30258472,
        properties_hs_date_entered_30258473,
        properties_hs_date_entered_30258477,
        properties_hs_date_exited_30258471,
        properties_hs_date_exited_30258472,
        properties_hs_date_exited_30258473,
        properties_hs_deal_stage_probability,
        properties_hs_deal_stage_probability_shadow,
        properties_hs_is_closed,
        properties_hs_is_closed_won,
        properties_hs_is_deal_split,
        properties_hs_lastmodifieddate,
        properties_hs_num_associated_active_deal_registrations,
        properties_hs_num_associated_deal_registrations,
        properties_hs_num_associated_deal_splits,
        properties_hs_num_target_accounts,
        properties_hs_object_id,
        properties_hs_projected_amount,
        properties_hs_projected_amount_in_home_currency,
        properties_hs_time_in_30258471,
        properties_hs_time_in_30258472,
        properties_hs_time_in_30258473,
        properties_hs_time_in_30258477,
        properties_hs_updated_by_user_id,
        properties_hs_user_ids_of_all_owners,
        properties_hubspot_owner_assigneddate,
        properties_hubspot_owner_id,
        properties_hubspot_team_id,
        properties_notes_last_contacted,
        properties_notes_last_updated,
        properties_num_associated_contacts,
        properties_num_contacted_notes,
        properties_num_notes,
        properties_pipeline,
        properties_produto_bv,
        year,
        month,
        day

    from source

)

select * from renamed
