version: 2

sources:
  - name: escaleos_eventhub 
    schema: trusted_escaleos_eventhub
    database: hive_metastore
    tables:
      - name: eventhub_attribution

  - name: homeservices_claro
    catalog: hive_metastore
    schema: trusted_homeservices_claro
    tables:
      - name: bing_ads_insights
      - name: facebook_ads_insights
      - name: google_ads_ad_group
  
  - name: homeservices_pdp
    catalog: hive_metastore
    schema: trusted_homeservices_pdp
    tables:
      - name: bing_ads_insights
      - name: facebook_ads_insights
      - name: google_ads_ad_group